### ISSUE TITLE
.kitchen.yml blocked by .gitignore

### ISSUE THREAD

**Issue by alexmbird** [ptqa/chef-scollector#4]
`README.md` refers to kitchen tests for the cookbook but `.kitchen.ym` is missing.  On closer inspection this is because the `.gitignore` contains:

```
.kitchen/
.kitchen.local.yml
.kitchen.yml
```

Is this in error?  I'm doing some work to add support for CentOS and would like to build upon the existing tests.

**Comment by ptqa** [comment]
@alexmbird  no, it's not an error. AFAIU kitchen.yml supposed to be created by user, so you can use driver and images that you want.

**Comment by alexmbird** [comment]
@ptqa I understand.  Could you perhaps ship the project with an example one?

**Comment by ptqa** [comment]
As far as I can see you've managed to do it by yourself.
